#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfcfa;
constexpr uint24_t FX_DATA_BYTES = 194034;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

constexpr uint24_t Level_00 = 0x000000;
constexpr uint24_t Level_01 = 0x0000FE;
constexpr uint24_t Level_02 = 0x000201;
constexpr uint24_t Level_03 = 0x0002E9;
constexpr uint24_t Level_04 = 0x0003E2;
constexpr uint24_t Level_05 = 0x0004CA;
constexpr uint24_t Level_06 = 0x0005AD;
constexpr uint24_t Level_07 = 0x0006B4;
constexpr uint24_t Level_08 = 0x0007C5;
constexpr uint24_t Level_09 = 0x000902;
constexpr uint24_t Level_10 = 0x000A1F;
constexpr uint24_t Level_11 = 0x000BAA;
constexpr uint24_t Level_12 = 0x000D53;
constexpr uint24_t Level_13 = 0x000E97;
constexpr uint24_t Level_14 = 0x001015;
constexpr uint24_t Level_15 = 0x00115A;
constexpr uint24_t Level_16 = 0x0012C4;
constexpr uint24_t Level_17 = 0x001475;
constexpr uint24_t Level_18 = 0x001628;
constexpr uint24_t Level_19 = 0x0017E6;
constexpr uint24_t Level_20 = 0x001A0F;
constexpr uint24_t Level_21 = 0x001AFC;
constexpr uint24_t Level_22 = 0x001C6C;
constexpr uint24_t Level_23 = 0x001D7F;
constexpr uint24_t Level_24 = 0x001F69;
constexpr uint24_t Level_25 = 0x002194;
constexpr uint24_t Level_26 = 0x00233B;
constexpr uint24_t Level_27 = 0x002531;
constexpr uint24_t Level_28 = 0x0026C0;
constexpr uint24_t Level_29 = 0x002895;
constexpr uint24_t Levels = 0x002A03;
namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x002A5D;
  constexpr uint24_t SFX_Three_Inc = 0x00A54E;
  constexpr uint24_t SFX_Three_Dec = 0x00A56A;
  constexpr uint24_t SFX_Death = 0x00A586;
  constexpr uint24_t SFX_Victory = 0x00A63A;
  constexpr uint24_t SFX_XPGain = 0x00A6EE;
}

namespace Images
{
  constexpr uint24_t Tile_FullRow = 0x00A702;
  constexpr uint24_t Tile_HalfRow = 0x00A8C0;
  constexpr uint24_t Rotator_1_00 = 0x00AA7E;
  constexpr uint24_t Rotator_1_01 = 0x00AAC8;
  constexpr uint24_t Rotator_1_02 = 0x00ABEA;
  constexpr uint24_t Rotator_1_03 = 0x00AC4C;
  constexpr uint24_t Rotator_1_04 = 0x00AD6E;
  constexpr uint24_t Rotator_1_05 = 0x00ADB8;
  constexpr uint24_t Rotator_1_06 = 0x00AEDA;
  constexpr uint24_t Rotator_1_07 = 0x00AF3C;
  constexpr uint24_t Rotator_2_00_OW = 0x00B05E;
  constexpr uint24_t Rotator_2_00_MK = 0x00B0F0;
  constexpr uint24_t Rotator_2_01_MK = 0x00B212;
  constexpr uint24_t Rotator_2_02_OW = 0x00B394;
  constexpr uint24_t Rotator_2_02_MK = 0x00B426;
  constexpr uint24_t Rotator_2_03_MK = 0x00B548;
  constexpr uint24_t Rotator_2_04_OW = 0x00B6FA;
  constexpr uint24_t Rotator_2_04_MK = 0x00B78C;
  constexpr uint24_t Rotator_2_05_MK = 0x00B8AE;
  constexpr uint24_t Rotator_2_06_OW = 0x00BA30;
  constexpr uint24_t Rotator_2_06_MK = 0x00BAC2;
  constexpr uint24_t Rotator_2_07_MK = 0x00BBE4;
  constexpr uint24_t Rotator_3_00_OW = 0x00BD96;
  constexpr uint24_t Rotator_3_00_MK = 0x00BE70;
  constexpr uint24_t Rotator_3_01_MK = 0x00C022;
  constexpr uint24_t Rotator_3_02_OW = 0x00C264;
  constexpr uint24_t Rotator_3_02_MK = 0x00C326;
  constexpr uint24_t Rotator_3_03_MK = 0x00C4A8;
  constexpr uint24_t Rotator_3_04_OW = 0x00C6EA;
  constexpr uint24_t Rotator_3_05_MK = 0x00C7C4;
  constexpr uint24_t Rotator_3_06_OW = 0x00CA06;
  constexpr uint24_t Rotator_3_06_MK = 0x00CAC8;
  constexpr uint24_t Rotator_3_07_MK = 0x00CC4A;
  constexpr uint24_t Rotator_4_00_MK = 0x00CE8C;
  constexpr uint24_t Rotator_4_01_MK = 0x00D0CE;
  constexpr uint24_t Rotator_5_00_OW = 0x00D310;
  constexpr uint24_t Rotator_5_01_MK = 0x00D372;
  constexpr uint24_t Rotator_5_02_OW = 0x00D5B4;
  constexpr uint24_t Rotator_5_03_MK = 0x00D646;
  constexpr uint24_t Rotator_5_04_OW = 0x00D888;
  constexpr uint24_t Rotator_5_05_MK = 0x00D8EA;
  constexpr uint24_t Rotator_5_06_OW = 0x00DB2C;
  constexpr uint24_t Rotator_5_07_MK = 0x00DBBE;
  constexpr uint24_t Menu = 0x00DE00;
  constexpr uint24_t Numbers_1D_WB = 0x012902;
  constexpr uint24_t Numbers_2D_WB = 0x0129B8;
  constexpr uint24_t Title = 0x013A22;
  constexpr uint24_t Tick = 0x02BA24;
  constexpr uint24_t Tile_04_02 = 0x02BA38;
  constexpr uint24_t Tile_04_03 = 0x02BA6A;
  constexpr uint24_t Tile_04_04 = 0x02BAB4;
  constexpr uint24_t Tile_04_05 = 0x02BB16;
  constexpr uint24_t Tile_05_02 = 0x02BB90;
  constexpr uint24_t Tile_05_03 = 0x02BBC2;
  constexpr uint24_t Tile_05_04 = 0x02BC0C;
  constexpr uint24_t Tile_05_05 = 0x02BC6E;
  constexpr uint24_t Tile_10_02 = 0x02BCE8;
  constexpr uint24_t Tile_10_03 = 0x02BD1A;
  constexpr uint24_t Tile_10_04 = 0x02BD64;
  constexpr uint24_t Tile_10_05 = 0x02BDC6;
  constexpr uint24_t Block_02_01 = 0x02BE40;
  constexpr uint24_t Block_03_01 = 0x02BEA2;
  constexpr uint24_t Block_04_01 = 0x02BF34;
  constexpr uint24_t Block_05_01 = 0x02BFF6;
  constexpr uint24_t PPOT = 0x02C0E8;
  constexpr uint24_t Sound_Volume = 0x02F0EA;
  constexpr uint24_t Sound_Checkbox = 0x02F50C;
  constexpr uint24_t Rotator_1 = 0x02F51A;
  constexpr uint24_t Rotator_2_MK = 0x02F532;
  constexpr uint24_t Rotator_2_OW = 0x02F54A;
  constexpr uint24_t Rotator_3_MK = 0x02F562;
  constexpr uint24_t Rotator_3_OW = 0x02F57A;
  constexpr uint24_t Rotator_5_OW = 0x02F592;
  constexpr uint24_t Rotator_5_MK = 0x02F5AA;
  constexpr uint24_t Tile_04 = 0x02F5C2;
  constexpr uint24_t Tile_05 = 0x02F5CE;
  constexpr uint24_t Tile_10 = 0x02F5DA;
  constexpr uint24_t Blocks_XX_01 = 0x02F5E6;
}

